version: '3'
services:
  api:
    image: leftbraincreated/flowfrenz-express:1.1.9
    build: ./marketplace/backend
    hostname: api
    environment:
      - PORT=8020
      - GOERLI_API_KEY=kvhdPMXOOmyz7VFub3ilwgT8Toqn5MU2
      - CORS_ORIGIN=http://localhost
      # - CORS_ORIGIN=http://marketplace.flowfrenznft.com
      - MONGO_USER=frenz_admin
      - MONGO_PW=H8yJCbG2zcWwpP
      - MONGO_HOST=localhost
    ports:
      - 8020:8020
    restart: unless-stopped

  mp1:
    image: leftbraincreated/flowfrenz-marketplace:1.1.17
    build: ./marketplace/ui
    hostname: mp1
    ports:
      - 8010:80
    restart: unless-stopped

  nginx:
    image: leftbraincreated/flowfrenz-host:1.1.7
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - mp1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - mp1

  # certbot:
  #   image: certbot/certbot:latest
  #   volumes:
  #     - ./certbot/www/:/var/www/certbot/:rw
  #     - ./certbot/conf/:/etc/letsencrypt/:rw
  #   depends_on:
  #     - nginx

  mongo:
    image: mongo
    restart: always
    volumes:
      - ./mongo_data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: frenz_admin
      MONGO_INITDB_ROOT_PASSWORD: H8yJCbG2zcWwpP

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: frenz_admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: H8yJCbG2zcWwpP
      ME_CONFIG_MONGODB_URL: mongodb://frenz_admin:H8yJCbG2zcWwpP@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: frenz_admin
      ME_CONFIG_BASICAUTH_PASSWORD: H8yJCbG2zcWwpP
