version: '3'
services:
  api:
    image: leftbraincreated/flowfrenz-express:dev
    build: ./marketplace/backend
    hostname: api
    env_file:
      - ./marketplace/backend/.env.development
    environment:
      - PORT=8020
      - SEPOLIA_API_KEY=${SEPOLIA_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PW=${MONGO_PW}
      - MONGO_HOST=localhost
    ports:
      - 8020:8020
    restart: unless-stopped

  mp1:
    image: leftbraincreated/flowfrenz-marketplace:dev
    build: ./marketplace/ui
    hostname: mp1
    ports:
      - 8010:80
    restart: unless-stopped

  mp2:
    image: leftbraincreated/flowfrenz-marketplace:dev
    build: ./marketplace/ui
    hostname: mp2
    ports:
      - 8011:80
    restart: unless-stopped

  nginx:
    image: leftbraincreated/flowfrenz-host:dev
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - mp1
      - mp2
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - mp1
      - mp2
