version: '3'
services:
  api:
    image: leftbraincreated/flowfrenz-express:1.1.10
    build: ./marketplace/backend
    hostname: api
    env_file:
      - ./marketplace/backend/.env
    environment:
      - PORT=8020
      - SEPOLIA_API_KEY=${SEPOLIA_API_KEY}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - MONGO_USER=${MONGO_USER}
      - MONGO_PW=${MONGO_PW}
      - MONGO_HOST=localhost
    ports:
      - 8020:8020
    restart: unless-stopped

  mp1:
    image: leftbraincreated/flowfrenz-marketplace:1.1.21
    build: ./marketplace/ui
    hostname: mp1
    ports:
      - 8010:80
    restart: unless-stopped

  nginx:
    image: leftbraincreated/flowfrenz-host:1.1.7
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - mp1
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - mp1

  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
    depends_on:
      - nginx

  mongo:
    image: mongo
    restart: always
    env_file:
      - ./marketplace/backend/.env
    volumes:
      - ./mongo_data/db:/data/db
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PW}

  mongo-express:
    image: mongo-express
    restart: always
    env_file:
      - ./marketplace/backend/.env
    ports:
      - 8081:8081
    links:
      - mongo
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: ${MONGO_USER}
      ME_CONFIG_MONGODB_ADMINPASSWORD: ${MONGO_PW}
      ME_CONFIG_MONGODB_URL: mongodb://${EXPRESS_USER}:${EXPRESS_PASSWORD}@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: ${EXPRESS_USER}
      ME_CONFIG_BASICAUTH_PASSWORD: ${EXPRESS_PASSWORD}
