version: '3'
services:
  api:
    # image: leftbraincreated/flowfrenz-express:1.1.3
    image: leftbraincreated/flowfrenz-express:dev
    build: ./marketplace/backend
    hostname: api
    environment:
      - PORT=8020
      - GOERLI_API_KEY=kvhdPMXOOmyz7VFub3ilwgT8Toqn5MU2
      - CORS_ORIGIN=http://localhost
      # - CORS_ORIGIN=http://marketplace.flowfrenznft.com
    ports:
      - 8020:8020
    restart: unless-stopped

  mp1:
    # image: leftbraincreated/flowfrenz-marketplace:1.1.4
    image: leftbraincreated/flowfrenz-marketplace:dev
    build: ./marketplace/ui
    hostname: mp1
    ports:
      - 8010:80
    restart: unless-stopped

  mp2:
    # image: leftbraincreated/flowfrenz-marketplace:1.1.4
    image: leftbraincreated/flowfrenz-marketplace:dev
    build: ./marketplace/ui
    hostname: mp2
    ports:
      - 8011:80
    restart: unless-stopped

  nginx:
    # image: leftbraincreated/flowfrenz-host:1.1.6
    image: leftbraincreated/flowfrenz-host:dev
    build: ./nginx
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www/:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
    links:
      - mp1
      - mp2
    ports:
      - 80:80
      - 443:443
    depends_on:
      - api
      - mp1
      - mp2
